### ISSUE TITLE
Validar

### ISSUE THREAD

**Issue by gabycasti** [PazAutumn/cardify#11]
Validar que las extension de los archivos correspondan a una imagen (.jpg, .jpeg o .png) ya que nuestra API solo se aplica a imágenes.

**Comment by gabycasti** [comment]
debemos validar que exista el atributo `alt` en la etiqueta `<img>` y que este contenga texto, ya que de ahí obtendremos el texto para mostrarlo en el `<figcaption>`

**Comment by PazAutumn** [comment]
Hay que preguntarle a Fabián igual sobre los test

**Comment by PazAutumn** [comment]
los test sobre la extensión del archivo está listo!

**Comment by PazAutumn** [comment]
el test para comprobar que alt sea un string está listo!
