### ISSUE TITLE
Completar Readme

### ISSUE THREAD

**Issue by PazAutumn** [PazAutumn/cardify#3]
Completar descripción y agregar totalidad de herramientas utilizadas

**Comment by PazAutumn** [comment]
Falta cambiar la descripción y explicar con más detalle que hace nuestra API

**Comment by gabycasti** [comment]
Y como podría hacer uso el usuario de nuestra API, paso por paso de manera explicativa

**Comment by PazAutumn** [comment]
Creo que deberíamos preguntarle a los profes sobre como poder subir nuestra API para que la gente pueda instalarla, o bien averiguar sobre eso en internet, así podemos agregar la instalación en el readme, quizás en la descripción podríamos poner algo como; "Esta Librería permite mostrar el `<figcaption>` de una imagen al hacer hover en esta" y ahí explicar como lo hace.

**Comment by gabycasti** [comment]
Si buena idea para que logremos explicarle al usuario de la manera mas sencilla posible y que nuestra Api sea muy sencilla de usar

**Comment by PazAutumn** [comment]
Hay que corregir la redacción

**Comment by gabycasti** [comment]
okis

**Comment by PazAutumn** [comment]
Falta solo revisar unos pequeños detalles e incluir gif
