### ISSUE TITLE
Crear test

### ISSUE THREAD

**Issue by PazAutumn** [PazAutumn/cardify#5]
crear dos test con posibles errores de la aplicación

**Comment by gabycasti** [comment]
preguntarle a la ale dudas sobre el test

**Comment by PazAutumn** [comment]
logramos solucionar nuestras dudas sobre los test al preguntarle a Ale, Fabían y Marcia y pudimos hacerlos correr

**Comment by PazAutumn** [comment]
#11 hecho!
